### ISSUE TITLE
Release OIDC support

### ISSUE THREAD

**Issue by johanneswuerbach** [hjacobs/kube-resource-report#110]
I would love to see a new release with https://github.com/hjacobs/kube-resource-report/commit/effc2c73b576c4b2b8297533ca44c30444564fe4 as this adds OIDC support https://github.com/hjacobs/pykube/pull/41 and allows us to run kube-resource-report without any further configuration changes 👏 

Would a new release be possible (with new docker images) be possible?

Thank you 🙇

**Comment by hjacobs** [comment]
Sure!

**Comment by hjacobs** [comment]
Done: https://github.com/hjacobs/kube-resource-report/releases/tag/19.9.0
