### ISSUE TITLE
Cannot get prices for N2 GCP instances

### ISSUE THREAD

**Issue by floretan** [hjacobs/kube-resource-report#116]
The `pricing.py` pulls data from https://cloudpricingcalculator.appspot.com/static/data/pricelist.json?v=1563953523378, and this includes pricing for the newer N2 instances. However, the related entries don't match the `CP-COMPUTEENGINE-VMIMAGE-` prefix, so these prices are left out.

**Comment by mgoodness** [comment]
Also N2D. PR inbound.
