### ISSUE TITLE
sort ingress by status code

### ISSUE THREAD

**Issue by szuecs** [hjacobs/kube-resource-report#12]
If you would sort by status code decreasing, then you find easily old broken ingress resources.

**Comment by hjacobs** [comment]
@szuecs actually all columns can be sorted by clicking on the column title (Javascript "sortable" library), so this is already possible with a single click :smile: 

Example: 
![screenshot-2018-6-6 cluster aws 061073533986 eu-central-1 kube-1 - kubernetes resource report](https://user-images.githubusercontent.com/510328/41006724-0c11d0d2-6923-11e8-9914-c273aab2d7b8.png)

Is this good enough for you?

**Comment by szuecs** [comment]
Ohje, as far as I remember I could only sort by name and not status but this might be my browser
