### ISSUE TITLE
CPU/Memory usage calculation and time frame

### ISSUE THREAD

**Issue by dneuhaeuser-zalando** [hjacobs/kube-resource-report#13]
First question looking at the cpu and memory usage of some of our applications was how the usage is calculated. Is this a min/max/avg per day/week/month? 

We have an application that just consists of a cronjob that shows up as having 0 CPU and memory usage, even though when though it should use quite a lot of memory when it's running.

**Comment by hjacobs** [comment]
The usage is currently retrieved via Heapster metrics and is just a "current" snapshot (I believe last 5 minutes or similar). This is clearly not optimal and just a first indication.

**Comment by hjacobs** [comment]
See #23 to fix the limited timeframe (it's actually only one minute atm).
