### ISSUE TITLE
GKE preemptible nodes not identified

### ISSUE THREAD

**Issue by carlpett** [hjacobs/kube-resource-report#139]
GKE preemptible nodes do not seem to be correctly identified as such, and the pricing shown is for non-preemptibles. In the pricing list csv it seems the assumption is that the instance type would contain the `-preemptible` suffix, which it does not.

For illustration, here are the labels set on a n1-standard-2 preemptible node:
```
beta.kubernetes.io/arch=amd64
beta.kubernetes.io/fluentd-ds-ready=true
beta.kubernetes.io/instance-type=n1-standard-2
beta.kubernetes.io/os=linux
cloud.google.com/gke-nodepool=n1-standard-2-preemptible # Note that this is just the name we've given it, it is not guaranteed to be the node type
cloud.google.com/gke-os-distribution=cos
cloud.google.com/gke-preemptible=true
failure-domain.beta.kubernetes.io/region=us-central1
failure-domain.beta.kubernetes.io/zone=us-central1-a
kubernetes.io/arch=amd64
kubernetes.io/hostname=gke-bs-n1-standard-2-preemptible-9d199f38-jxz2
kubernetes.io/os=linux
```

The "easy" way would be to add a check if `cloud.google.com/gke-preemptible=true` and if so append `-preemptible` to the type here:
https://github.com/hjacobs/kube-resource-report/blob/25bab83cbc48585621dda95bab702a5b8f882760/kube_resource_report/report.py#L317

Would this be acceptable?

**Comment by hjacobs** [comment]
Would you be willing to do a PR?

**Comment by carlpett** [comment]
Sure, just wanted to make sure it was an acceptable approach :) I'll open one during the day!
