### ISSUE TITLE
Sorting by column broken after 20.3.1

### ISSUE THREAD

**Issue by carlpett** [hjacobs/kube-resource-report#144]
Upgrading from 20.3.1 to 20.4.1, I can no longer sort tables by clicking the column headers. It appears the `th` elements no longer get a click event handler added?

**Comment by hjacobs** [comment]
This still works in 20.4.1 for me (at least in Firefox), you can try it here: https://kube-resource-report.demo.j-serv.de/pods.html

![Screenshot_2020-04-14 Applications - Kubernetes Resource Report](https://user-images.githubusercontent.com/510328/79203569-84899200-7e3b-11ea-9a64-ee9d4ee9294a.png)

**Comment by hjacobs** [comment]
Update: also works in Chromium (80.0) for me.

**Comment by carlpett** [comment]
Odd. Your demo site works for me (FF 73), but our internal deployment does not. Even after clearing all caches etc.
But this then seems like something broken in our deployment somehow, not a bug here. Thanks for the, eh, non-repro :)
