### ISSUE TITLE
return "" for ingress apiVersion

### ISSUE THREAD

**Issue by gitkent** [hjacobs/kube-resource-report#145]
Hi chaps,

I got the following when deploying from `master` branch:

 └─ $ ▶ helm version
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}

 └─ $ ▶ helm upgrade --install --debug --dry-run --kube-context mycontext --namespace=mynamespace --values=./values/kube-resource-report/values-np.yaml kube-resource-report-np ./chart/kube-resource-report
Release "kube-resource-report-np" does not exist. Installing it now.
[debug] CHART PATH: /Users/myName/Documents/workplace/gitlab/kube-resource-report_k8s/chart/kube-resource-report

Error: unable to recognize "": no matches for kind "Ingress" in version ""

Can anyone please help?

**Comment by hjacobs** [comment]
I'm not using Helm myself. I merged #136, could you check if the Helm chart works now?

**Comment by gitkent** [comment]
Thanks for your response. Yes it works now. Now just one of the container is not coming up due to another issue which I'd raised another issue about it. [#146 ](url)
