### ISSUE TITLE
add kustomize;  and/or move one of the deployment/configmap out of deploy

### ISSUE THREAD

**Issue by yashbhutwala** [hjacobs/kube-resource-report#153]
- [x] add kustomization (solved by #149)
- [x] move `deployment-with-cm.yaml` and `configmap.yaml` out of base deploy/ folder, because otherwise `kubectl apply -f deploy/` is not correct

**Comment by hjacobs** [comment]
Can you explain what value Kustomize would add? I tend to clean up the `deploy/` folder instead.

**Comment by yashbhutwala** [comment]
not much, but theoretically, you can support both workflows, i.e.: `kubectl apply -f` and `kubectl apply -k <url>`.  kustomize has ability to build from [remote targets](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md) so someone can directly apply the yamls with a url to the directory rather than having to clone the repo and/or modify their yamls using the url as base.

**Comment by hjacobs** [comment]
I removed one of the deployment YAMLs.

**Comment by yashbhutwala** [comment]
sounds good ma dude, what about the pricing data for gcp?
