### ISSUE TITLE
Support multiple clusters using k8s configuration files

### ISSUE THREAD

**Issue by larrycai** [hjacobs/kube-resource-report#175]
So far it looks like it uses different ways to support multiple clusters, is it possible to support to use several kube-config files like 

````
--clusters kube-config1,kube-config2
````

**Comment by hjacobs** [comment]
You can configure multiple clusters in your kubeconfig (`~/.kube/config`) and kube-resource-report will use all of them.

**Comment by larrycai** [comment]
Oh, yes, this is a working solution to combine my all configuration into one. 

And it works nicely.

thx.
