### ISSUE TITLE
Keep historic metrics for higher accuracy

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-resource-report#23]
We currently rely on snapshot metrics from Metrics API (Heapster) which only has data for the last minute. Having some historic data would be desirable to compensate for volatile usage patterns (e.g. one pod could spike in the minute we observe it or vice versa, i.e. it might usually use more resource).

**Comment by tomislater** [comment]
Hmm, what about providing metrics for Prometheus? It should be easy to implement, all metrics are here. We just need to put them to a txt file and serve via nginx? What do you think?
