### ISSUE TITLE
Charts legend

### ISSUE THREAD

**Issue by mrandi** [hjacobs/kube-resource-report#41]
![image](https://user-images.githubusercontent.com/4638986/44776078-7fe56c80-ab77-11e8-808b-8509378c3938.png)

Would be great to have a legend with a mouse hover or somewhere in the page.
Is not clear what are the color representing.

**Comment by hjacobs** [comment]
Yes, sounds useful!

**Comment by leosunmo** [comment]
This would be very useful. In the meantime, where can I get an explanation of these bars @hjacobs ?

**Comment by hjacobs** [comment]
@leosunmo I guess I need to write up some docs/blog post, but here the quick info:

* light-grey bar: total allocatable resources (only for nodes/clusters)
* dark grey bar: resource requests
* green bar: resource usage

for pods/apps the left number is the resource usage and the right number is the resource requests

**Comment by mrandi** [comment]
@hjacobs I created a simple PR, let me know if is ok like this.
