### ISSUE TITLE
Read available clusters from $KUBECONFIG

### ISSUE THREAD

**Issue by kivagant-ba** [hjacobs/kube-resource-report#72]
I have `$KUBECONFIG` which contains several paths and I can't find a way how to ask the tool to read one of them that is not in `~/.kube/config`.

It would be nice if `kube-resource-report` reads all available configurations from $KUBECONFIG as `kubectl` does.

**Comment by hjacobs** [comment]
So your `KUBECONFIG` env var contains a string with multiple paths separated by colon (":")?

**Comment by kivagant-ba** [comment]
Yes, that's true

**Comment by MarcusPorterAtQuestDiagnostics** [comment]
You can merge them to make a single file just for kube-resource-report as follows:
  kubectl config view --flatten >new-kubeconfig
