### ISSUE TITLE
Only metrics of current namespace

### ISSUE THREAD

**Issue by BouweCeunen** [hjacobs/kube-resource-report#76]
With 0.9 I'm only getting metrics for the pods of the namespace where kube-resource-report is located in, not having this issue with 0.8.

**Comment by hjacobs** [comment]
Yes, damn it, my mistake, will fix!

**Comment by hjacobs** [comment]
Should be fixed in https://github.com/hjacobs/kube-resource-report/releases/tag/0.9.1
