### ISSUE TITLE
Clean up (remove) stale HTML files

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-resource-report#84]
The script does not currently remove HTML files which are no longer generated (e.g. if a cluster/team/application was shut down and no longer exists).

**Comment by tomislater** [comment]
Hmm, I think this has been implemented: https://github.com/hjacobs/kube-resource-report/commit/94c3754b62e0ce800abaeb931db1c7000c3a7c67

**Comment by hjacobs** [comment]
Yes, this was implemented!
